# frozen_string_literal: true

module Easyop
  module PersistentFlow
    # AR model mixin for EasyFlowRunStep.
    #
    # Include in your model (generated by the installer):
    #   class EasyFlowRunStep < ApplicationRecord
    #     include Easyop::PersistentFlow::FlowRunStepModel
    #   end
    module FlowRunStepModel
      def self.included(base)
        base.extend(ClassMethods)
      end

      module ClassMethods; end

      def completed?; status == 'completed'; end
      def failed?;    status == 'failed';    end
      def skipped?;   status == 'skipped';   end
      def running?;   status == 'running';   end
    end
  end
end
