# frozen_string_literal: true

module Easyop
  module PersistentFlow
    # AR model mixin for EasyFlowRun.
    #
    # Include in your model (generated by the installer):
    #   class EasyFlowRun < ApplicationRecord
    #     include Easyop::PersistentFlow::FlowRunModel
    #   end
    module FlowRunModel
      def self.included(base)
        base.extend(ClassMethods)
      end

      module ClassMethods; end

      TERMINAL_STATUSES = %w[succeeded failed cancelled].freeze

      # ── Status predicates ────────────────────────────────────────────────────

      def pending?;   status == 'pending';   end
      def running?;   status == 'running';   end
      def paused?;    status == 'paused';    end
      def succeeded?; status == 'succeeded'; end
      def failed?;    status == 'failed';    end
      def cancelled?; status == 'cancelled'; end
      def terminal?;  TERMINAL_STATUSES.include?(status); end

      # ── Lifecycle ────────────────────────────────────────────────────────────

      def cancel!
        return self if terminal?

        update!(status: 'cancelled', finished_at: Time.current)
        Easyop::Scheduler.cancel_by_tag("flow_run:#{id}") if defined?(Easyop::Scheduler)
        self
      end

      def pause!
        return self unless running?

        update!(status: 'paused')
        Easyop::Scheduler.cancel_by_tag("flow_run:#{id}") if defined?(Easyop::Scheduler)
        self
      end

      def resume!
        return self unless paused?

        update!(status: 'running')
        Easyop::PersistentFlow::Runner.advance!(self)
        self
      end

      # Resolves the polymorphic subject AR record (set via `subject :user`).
      def subject
        return nil unless subject_type && subject_id

        subject_type.constantize.find(subject_id)
      end
    end
  end
end
