#!/usr/bin/env ruby
# frozen_string_literal: true

# 08 — Durable Flows (v0.5 unified API)
#
# Covers:
#   include Easyop::Flow + subject :user   — triggers durable mode (Mode 3)
#   subject stored as subject_type/subject_id on FlowRun row
#   flow steps run durable — ctx persisted across async boundaries
#   on_exception(:reattempt!, max_reattempts: N) — automatic retry
#   on_exception(:cancel!)                 — fail immediately on step error
#   async_retry max_attempts:, backoff:    — operation-level retry policy
#   Op.async(blocking: true)               — skip remaining steps on final failure
#   flow_run.cancel!                       — cancel from outside the flow
#   flow_run.resume!                       — resume a paused flow
#   Free composition — outer plain flow embeds a durable inner → auto-promotes
#
# Note: uses in-memory FakeFlowRun/FakeFlowRunStep/FakeScheduledTask stubs
#       (no database needed). In a Rails app, use the EasyFlowRun/EasyFlowRunStep
#       AR models generated by `rails g easyop:install`.
#
# Run: ruby examples/code/08_durable_workflow.rb

$LOAD_PATH.unshift File.expand_path('../../lib', __dir__)
require 'easyop'
require 'easyop/persistent_flow'
require 'easyop/scheduler'
require 'easyop/plugins/async'

# Time.current shim (ActiveSupport not required here)
unless Time.respond_to?(:current)
  class Time
    def self.current; now; end
  end
end

# String#constantize shim (ActiveSupport not required here)
unless ''.respond_to?(:constantize)
  class String
    def constantize; Object.const_get(self); end
  end
end

# ── Minimal AR stubs (no database) ────────────────────────────────────────────

class FakeScope
  include Enumerable

  def initialize(records) = @records = records
  def each(&blk)          = @records.each(&blk)
  def count               = @records.size
  def first               = @records.first
  def exists?             = @records.any?

  def where(*args, **conditions)
    return self if args.any? && conditions.empty?

    FakeScope.new(@records.select do |r|
      conditions.all? { |k, v| r.public_send(k) == v }
    end)
  end

  def update_all(**attrs)
    @records.each { |r| attrs.each { |k, v| r.public_send(:"#{k}=", v) } }
    @records.size
  end
end

class FakeFlowRun
  include Easyop::PersistentFlow::FlowRunModel

  attr_accessor :id, :flow_class, :context_data, :status, :current_step_index,
                :subject_type, :subject_id, :started_at, :finished_at

  @@store      = []
  @@id_counter = 0

  def self.store;   @@store;   end
  def self.reset!;  @@store = []; @@id_counter = 0; end

  def self.create!(attrs)
    obj = new
    attrs.each { |k, v| obj.public_send(:"#{k}=", v) }
    @@id_counter += 1
    obj.id = @@id_counter
    @@store << obj
    obj
  end

  def self.find(id)
    @@store.find { |r| r.id == id.to_i } or raise "FakeFlowRun #{id} not found"
  end

  def self.where(*args, **conditions)
    return FakeScope.new(@@store) if args.any? && conditions.empty?

    FakeScope.new(@@store.select do |r|
      conditions.all? { |k, v| r.public_send(k) == v }
    end)
  end

  def initialize
    @status             = 'pending'
    @current_step_index = 0
    @context_data       = '{}'
  end

  def update!(attrs)    = attrs.each { |k, v| public_send(:"#{k}=", v) } && self
  def update_columns(a) = update!(a)
  def reload            = self
end

class FakeFlowRunStep
  include Easyop::PersistentFlow::FlowRunStepModel

  attr_accessor :id, :flow_run_id, :step_index, :operation_class, :status,
                :attempt, :error_class, :error_message, :started_at, :finished_at

  @@store      = []
  @@id_counter = 0

  def self.store;   @@store;   end
  def self.reset!;  @@store = []; @@id_counter = 0; end

  def self.create!(attrs)
    obj = new
    attrs.each { |k, v| obj.public_send(:"#{k}=", v) }
    @@id_counter += 1
    obj.id = @@id_counter
    @@store << obj
    obj
  end

  def self.find(id)
    @@store.find { |r| r.id == id.to_i } or raise "FakeFlowRunStep #{id} not found"
  end

  def self.where(*args, **conditions)
    return FakeScope.new(@@store) if args.any? && conditions.empty?

    FakeScope.new(@@store.select do |r|
      conditions.all? { |k, v| r.public_send(k) == v }
    end)
  end

  def initialize
    @status  = 'running'
    @attempt = 0
  end

  def update_columns(attrs) = attrs.each { |k, v| public_send(:"#{k}=", v) } && self
end

class FakeScheduledTask
  attr_accessor :id, :operation_class, :ctx_data, :run_at, :tags, :state

  @@store      = []
  @@id_counter = 0

  def self.store;   @@store;   end
  def self.reset!;  @@store = []; @@id_counter = 0; end

  # Minimal connection stub so Scheduler._adapter_name does not raise
  def self.connection
    Struct.new(:adapter_name).new('fake_adapter')
  end

  def self.create!(attrs)
    obj = new
    attrs.each { |k, v| obj.public_send(:"#{k}=", v) if obj.respond_to?(:"#{k}=") }
    @@id_counter += 1
    obj.id    ||= @@id_counter
    obj.state ||= 'scheduled'
    @@store << obj
    obj
  end

  def self.find(id)   = @@store.find { |r| r.id == id }
  def self.where(*args, **conditions)
    return FakeScope.new(@@store) if args.any? && conditions.empty?

    FakeScope.new(@@store.select do |r|
      conditions.all? { |k, v| r.respond_to?(k) && r.public_send(k) == v }
    end)
  end

  def update_columns(attrs) = attrs.each { |k, v| public_send(:"#{k}=", v) if respond_to?(:"#{k}=") } && self

  def initialize
    @state = 'scheduled'
  end
end

# ── Configure Easyop to use our in-memory stubs ───────────────────────────────

Easyop.configure do |c|
  c.persistent_flow_model      = 'FakeFlowRun'
  c.persistent_flow_step_model = 'FakeFlowRunStep'
  c.scheduler_model            = 'FakeScheduledTask'
end

# ── Speedrun helper — drives all pending scheduled tasks synchronously ─────────

def speedrun(flow_run, max_iterations: 20)
  max_iterations.times do
    break if flow_run.terminal?
    # Find a pending task for this flow_run
    task = FakeScheduledTask.store.find do |t|
      t.state == 'scheduled' &&
        Easyop::Scheduler::Serializer.deserialize(t.ctx_data)[:flow_run_id] == flow_run.id
    end
    break unless task

    task.state = 'running'
    Easyop::PersistentFlow::Runner.execute_scheduled_step!(flow_run)
  end
  flow_run.reload
end

def reset_all!
  FakeFlowRun.reset!
  FakeFlowRunStep.reset!
  FakeScheduledTask.reset!
end

# ── Subject model — AR-compatible so Serializer can round-trip it ─────────────
# The Serializer stores AR objects as { __ar_class, __ar_id } and calls
# ClassName.find(id) on deserialization.

unless defined?(ActiveRecord)
  module ActiveRecord; class Base; end; end
end

class Subscriber < ActiveRecord::Base
  @@store = {}

  def self.store        = @@store
  def self.reset!       = (@@store = {})
  def self.find(id)     = @@store.fetch(id.to_i) { raise "Subscriber #{id} not found" }
  def self.create!(attrs)
    id = (@@store.keys.max || 0) + 1
    s  = new(id: id, **attrs)
    @@store[id] = s
    s
  end

  attr_accessor :id, :email, :active, :newsletter_opt_in

  def initialize(id: nil, email:, active:, newsletter_opt_in: true)
    @id              = id
    @email           = email
    @active          = active
    @newsletter_opt_in = newsletter_opt_in
    @@store[@id] = self if @id
  end
end

puts '─' * 50
puts '08 — Durable Flows'
puts '─' * 50

# ── Step classes ──────────────────────────────────────────────────────────────

class ValidateSubscription
  include Easyop::Operation

  def call
    ctx.fail!(error: 'Subscriber is not active') unless ctx.subscriber&.active
    ctx.plan = ctx[:plan] || 'basic'
  end
end

class ProcessPayment
  include Easyop::Operation
  plugin Easyop::Plugins::Async   # step-builder DSL (on_exception) requires Async plugin

  @@fail_count = 0

  def self.reset_fail_count!   = (@@fail_count = 0)
  def self.set_failures(n)     = (@@fail_count = n)

  def call
    if @@fail_count > 0
      @@fail_count -= 1
      raise 'payment gateway timeout'
    end

    ctx.payment_id = "pay_#{SecureRandom.hex(6)}"
    puts "  [ProcessPayment] charged #{ctx.subscriber.email} → #{ctx.payment_id}"
  end
end

class ActivateAccount
  include Easyop::Operation
  plugin Easyop::Plugins::Async   # step-builder DSL (.async) requires Async plugin

  def call
    ctx.activated = true
    puts "  [ActivateAccount] account activated for #{ctx.subscriber.email}"
  end
end

class SendWelcomeEmail
  include Easyop::Operation
  plugin Easyop::Plugins::Async   # enables .skip_if fluent builder

  def call
    puts "  [SendWelcomeEmail] welcome email sent to #{ctx.subscriber.email}"
    ctx.welcome_sent = true
  end
end

class NotifyBillingTeam
  include Easyop::Operation

  def call
    puts "  [NotifyBillingTeam] billing team notified for plan=#{ctx.plan}"
    ctx.billing_notified = true
  end
end

# ── Durable flow definition ───────────────────────────────────────────────────

class ProcessSubscription
  include Easyop::Flow

  subject :subscriber   # triggers Mode 3 — .call returns FlowRun

  flow ValidateSubscription,
       ProcessPayment.on_exception(:reattempt!, max_reattempts: 2),
       ActivateAccount,
       SendWelcomeEmail.skip_if { |ctx| !ctx[:subscriber]&.newsletter_opt_in },
       NotifyBillingTeam
end

# ── Scenario 1: Happy path — all steps complete ───────────────────────────────

puts "\nScenario 1 — happy path (newsletter opted in)"
reset_all!
ProcessPayment.reset_fail_count!
Subscriber.reset!

subscriber = Subscriber.create!(email: 'alice@example.com', active: true, newsletter_opt_in: true)
flow_run = ProcessSubscription.call(subscriber: subscriber, plan: 'pro')

puts "  returns FlowRun: #{flow_run.is_a?(FakeFlowRun)}"  # true
puts "  status:          #{flow_run.status}"               # succeeded
puts "  subject_type:    #{flow_run.subject_type}"         # Subscriber
puts "  subject_id:      #{flow_run.subject_id}"           # 1

steps = FakeFlowRunStep.store.select { |s| s.flow_run_id == flow_run.id }
puts "  step summary:"
steps.each { |s| puts "    #{s.operation_class.split('::').last.ljust(28)} #{s.status}" }

# ── Scenario 2: skip_if — newsletter opted out ────────────────────────────────

puts "\nScenario 2 — SendWelcomeEmail skipped (newsletter_opt_in: false)"
reset_all!
ProcessPayment.reset_fail_count!
Subscriber.reset!

subscriber2 = Subscriber.create!(email: 'bob@example.com', active: true, newsletter_opt_in: false)
flow_run2 = ProcessSubscription.call(subscriber: subscriber2)

puts "  status:            #{flow_run2.status}"   # succeeded
welcome = FakeFlowRunStep.store.find { |s| s.operation_class.include?('WelcomeEmail') }
puts "  SendWelcomeEmail:  #{welcome&.status}"    # skipped

# ── Scenario 3: on_exception :reattempt! — auto-retry then fail ───────────────

puts "\nScenario 3 — on_exception: :reattempt! (3 attempts then fail)"
reset_all!
ProcessPayment.set_failures(3)   # fails 3 times → exhausts max_reattempts: 2
Subscriber.reset!

subscriber3 = Subscriber.create!(email: 'carol@example.com', active: true)
flow_run3 = ProcessSubscription.call(subscriber: subscriber3)

# Runner.advance! ran ValidateSubscription then hit the first ProcessPayment failure
# → scheduled a retry. speedrun processes the retries.
speedrun(flow_run3)

puts "  status: #{flow_run3.status}"   # failed (all reattempts exhausted)
payment_attempts = FakeFlowRunStep.store.count do |s|
  s.flow_run_id == flow_run3.id && s.operation_class.include?('ProcessPayment')
end
puts "  ProcessPayment attempts: #{payment_attempts}"   # 3

# ── Scenario 4: on_exception :cancel! — immediate failure on step error ───────

puts "\nScenario 4 — on_exception: :cancel! (fail immediately)"
reset_all!
Subscriber.reset!

class PessimisticPayment
  include Easyop::Operation
  plugin Easyop::Plugins::Async   # step-builder DSL (on_exception) requires Async plugin

  def call
    raise 'gateway down'
  end
end

class CancelOnErrorFlow
  include Easyop::Flow
  subject :subscriber
  flow ValidateSubscription,
       PessimisticPayment.on_exception(:cancel!),
       ActivateAccount
end

subscriber4 = Subscriber.create!(email: 'dave@example.com', active: true)
flow_run4 = CancelOnErrorFlow.call(subscriber: subscriber4)

puts "  status:          #{flow_run4.status}"   # failed
puts "  steps completed: #{FakeFlowRunStep.store.count { |s| s.flow_run_id == flow_run4.id && s.status == 'completed' }}"
puts "  steps failed:    #{FakeFlowRunStep.store.count { |s| s.flow_run_id == flow_run4.id && s.status == 'failed' }}"

# ── Scenario 5: flow_run.cancel! — cancel from outside the flow ───────────────

puts "\nScenario 5 — flow_run.cancel! from outside"
reset_all!
Subscriber.reset!

class DelayedFlow
  include Easyop::Flow
  plugin Easyop::Plugins::Async
  subject :subscriber
  flow ValidateSubscription,
       ActivateAccount.async(wait: 86_400),   # 1-day async step → pauses here
       NotifyBillingTeam
end

subscriber5 = Subscriber.create!(email: 'eve@example.com', active: true)
flow_run5 = DelayedFlow.call(subscriber: subscriber5)
# Runner.advance! ran ValidateSubscription, then hit the async ActivateAccount
# → status is 'running', a FakeScheduledTask was created.

puts "  status after .call:        #{flow_run5.status}"   # running
puts "  scheduled tasks pending:   #{FakeScheduledTask.store.count { |t| t.state == 'scheduled' }}"  # 1

flow_run5.cancel!

puts "  status after .cancel!:     #{flow_run5.status}"   # cancelled
puts "  scheduled tasks remaining: #{FakeScheduledTask.store.count { |t| t.state == 'scheduled' }}"  # 0

# ── Scenario 6: subject stored on FlowRun row ─────────────────────────────────

puts "\nScenario 6 — subject stored on FlowRun row"
reset_all!
ProcessPayment.reset_fail_count!
Subscriber.reset!

sub6 = Subscriber.create!(email: 'frank@example.com', active: true)
fr6  = ProcessSubscription.call(subscriber: sub6)

puts "  subject_type: #{fr6.subject_type}"   # Subscriber
puts "  subject_id:   #{fr6.subject_id}"     # 1
puts "  resolved:     #{fr6.subject.email}"  # frank@example.com (re-fetched from Subscriber.find)

# ── Scenario 7: Free composition — outer plain flow auto-promotes ──────────────

puts "\nScenario 7 — free composition (plain outer embeds durable inner)"
reset_all!
ProcessPayment.reset_fail_count!
Subscriber.reset!

class PreFlightCheck
  include Easyop::Operation

  def call
    puts "  [PreFlightCheck] running pre-flight"
    ctx.preflight_done = true
  end
end

class InnerDurable
  include Easyop::Flow
  subject :subscriber
  flow ValidateSubscription, ActivateAccount
end

class OuterPlain
  include Easyop::Flow
  flow PreFlightCheck, InnerDurable   # no subject here — but inner has one
end

sub7  = Subscriber.create!(email: 'grace@example.com', active: true)
fr7   = OuterPlain.call(subscriber: sub7)

puts "  OuterPlain.call returns FlowRun: #{fr7.is_a?(FakeFlowRun)}"  # true — auto-promoted
puts "  flow_class:    #{fr7.flow_class}"    # OuterPlain
puts "  subject_type:  #{fr7.subject_type}"  # Subscriber (inherited from InnerDurable)
puts "  status:        #{fr7.status}"        # succeeded
steps7 = FakeFlowRunStep.store.select { |s| s.flow_run_id == fr7.id }
puts "  step summary:"
steps7.each { |s| puts "    #{s.operation_class.split('::').last.ljust(28)} #{s.status}" }

# ── Scenario 8: chained .async(wait:) steps — the canonical durable wait chain ─

puts "\nScenario 8 — chained .async(wait:) steps (durable wait chain)"
reset_all!
Subscriber.reset!

# Three operations whose execution is separated by wait windows.
# Each runs in its own scheduled task, with ctx persisted across boundaries.
class SendDay0Welcome
  include Easyop::Operation
  plugin Easyop::Plugins::Async

  def call
    puts "  [SendDay0Welcome] welcome email sent to #{ctx.subscriber.email}"
    ctx.welcome_sent = true
  end
end

class SendDay1Tips
  include Easyop::Operation
  plugin Easyop::Plugins::Async

  def call
    puts "  [SendDay1Tips]    day-1 tips sent  (wait: 60s elapsed)"
    ctx.tips_sent = true
  end
end

class SendDay7Nudge
  include Easyop::Operation
  plugin Easyop::Plugins::Async

  def call
    puts "  [SendDay7Nudge]   week-1 nudge sent  (wait: 120s elapsed)"
    ctx.nudge_sent = true
  end
end

class WelcomeDrip
  include Easyop::Flow
  plugin Easyop::Plugins::Async
  subject :subscriber   # Mode 3 — .call returns FlowRun

  # Three async steps chained in series, each separated by a wait window.
  # In production use 1.day / 7.days; small integers used here for speed.
  flow SendDay0Welcome.async,           # fires immediately
       SendDay1Tips.async(wait: 60),    # waits 60 seconds
       SendDay7Nudge.async(wait: 120)   # waits another 120 seconds
end

sub8  = Subscriber.create!(email: 'hana@example.com', active: true)
fr8   = WelcomeDrip.call(subscriber: sub8)

puts "  status after .call:         #{fr8.status}"         # running (first task queued)
puts "  scheduled tasks pending:    #{FakeScheduledTask.store.count { |t| t.state == 'scheduled' }}"  # 1

# speedrun drives all three async steps — each call to execute_scheduled_step!
# runs one op, persists ctx, then schedules the next task if another async step follows.
speedrun(fr8)

puts "  status after speedrun:      #{fr8.status}"          # succeeded

steps8 = FakeFlowRunStep.store.select { |s| s.flow_run_id == fr8.id }
puts "  completed steps:            #{steps8.count { |s| s.status == 'completed' }}"   # 3

# Verify ctx round-tripped correctly across async boundaries
final_ctx8 = Easyop::Scheduler::Serializer.deserialize(fr8.context_data)
puts "  ctx.welcome_sent:           #{final_ctx8[:welcome_sent]}"   # true
puts "  ctx.tips_sent:              #{final_ctx8[:tips_sent]}"      # true
puts "  ctx.nudge_sent:             #{final_ctx8[:nudge_sent]}"     # true

remaining8 = FakeScheduledTask.store.count { |t| t.state == 'scheduled' }
puts "  pending scheduled tasks:    #{remaining8}"                  # 0

# ── Scenario 9: Mode 2 contrast — .async steps WITHOUT subject ────────────────
#
# When a flow has NO `subject`, it runs in Mode 2 (fire-and-forget):
#   - .call returns Ctx (not FlowRun)
#   - Async steps are enqueued via call_async immediately (no persistence)
#   - There is no FlowRun row, no resume, no ctx round-trip
#   - wait: on a step DOES work in Mode 2 — it passes the delay to ActiveJob
#     (so the job fires N seconds later). But it can't suspend/resume like Mode 3.
#   - on_exception: and tags: are durable-only — raise PersistentFlowOnlyOptionsError
#
# Use Mode 2 when you just want a step to happen in the background after
# the synchronous steps complete (e.g., send an email, emit a webhook).
# Use Mode 3 (subject) when you need steps to run HOURS apart and resume
# from persisted ctx — that's what the chained wait chain from Scenario 8 is for.

puts "\nScenario 9 — Mode 2 contrast (no subject, fire-and-forget)"
reset_all!
Subscriber.reset!

class QuickEnrich
  include Easyop::Operation

  def call
    ctx.enriched = true
    puts "  [QuickEnrich] sync step ran inline"
  end
end

class FireAndForgetNotify
  include Easyop::Operation
  plugin Easyop::Plugins::Async

  def call
    puts "  [FireAndForgetNotify] async notification sent (background job in production)"
    ctx.notified = true
  end
end

class Mode2DemoFlow
  include Easyop::Flow
  flow QuickEnrich,
       FireAndForgetNotify.async   # no subject → Mode 2
end

# Capture the async call via the built-in spy so no real ActiveJob is needed
captured_mode2 = []
Thread.current[:_easyop_async_capture]      = captured_mode2
Thread.current[:_easyop_async_capture_only] = true   # capture only, don't execute

mode2_ctx = Mode2DemoFlow.call(name: 'World')

Thread.current[:_easyop_async_capture]      = nil
Thread.current[:_easyop_async_capture_only] = nil

puts "  .call returns Ctx:          #{mode2_ctx.is_a?(Easyop::Ctx)}"         # true
puts "  sync step ran:              #{mode2_ctx.enriched}"                    # true
puts "  async op captured:          #{captured_mode2.first&.dig(:operation)}" # FireAndForgetNotify
puts "  FlowRun rows created:       #{FakeFlowRun.store.size}"                # 0 — no persistence

# Confirm that durable-only options (on_exception:, tags:) raise an error in Mode 2.
# These options are only meaningful when a persistent Runner can act on them.
class BadMode2Flow
  include Easyop::Flow
  flow FireAndForgetNotify.async.on_exception(:reattempt!)   # on_exception: is durable-only
end

begin
  # Use spy to avoid real ActiveJob dependency
  Thread.current[:_easyop_async_capture]      = []
  Thread.current[:_easyop_async_capture_only] = true
  BadMode2Flow.call
  puts "  UNEXPECTED: should have raised PersistentFlowOnlyOptionsError"
rescue Easyop::Operation::StepBuilder::PersistentFlowOnlyOptionsError => e
  puts "  on_exception: without subject raises: #{e.class.name.split('::').last}"
ensure
  Thread.current[:_easyop_async_capture]      = nil
  Thread.current[:_easyop_async_capture_only] = nil
end

# ── Scenario 10: async_retry + blocking: — operation-level retry with flow halt ─

puts "\nScenario 10 — async_retry on operation class + blocking: on flow step"
reset_all!
Subscriber.reset!

# Operation declares its own retry policy — 2 total attempts, constant delay.
class FlakyEmailSender
  include Easyop::Operation
  plugin Easyop::Plugins::Async

  @@fail_count = 0
  def self.set_failures(n) = (@@fail_count = n)
  def self.reset_fail_count! = (@@fail_count = 0)

  # Declared on the operation class — not on every flow that uses it.
  async_retry max_attempts: 2, wait: 0, backoff: :constant

  def call
    if @@fail_count > 0
      @@fail_count -= 1
      raise 'SMTP unavailable'
    end
    puts "  [FlakyEmailSender] email sent successfully"
    ctx.email_sent = true
  end
end

class SendSurveyReminder
  include Easyop::Operation
  plugin Easyop::Plugins::Async

  def call
    puts "  [SendSurveyReminder] survey reminder sent"
    ctx.survey_sent = true
  end
end

# Flow: FlakyEmailSender is blocking — if it exhausts retries the remaining
# async steps are skipped and recorded as such.
class RetryBlockingFlow
  include Easyop::Flow
  subject :subscriber

  flow FlakyEmailSender.async(blocking: true),
       SendSurveyReminder.async(wait: 3600)
end

# ── Part A: FlakyEmailSender fails both attempts → flow fails, survey skipped

FlakyEmailSender.set_failures(99)   # always fail

sub10a = Subscriber.create!(email: 'grace@example.com', active: true)
fr10a  = RetryBlockingFlow.call(subscriber: sub10a)

# advance! schedules the first async step (status: running)
puts "  [Part A] status after .call: #{fr10a.status}"   # running

# speedrun drives each scheduled task synchronously until terminal or no tasks remain
speedrun(fr10a)

puts "  [Part A] final status:       #{fr10a.status}"   # failed

email_failures = FakeFlowRunStep.store.count { |s| s.flow_run_id == fr10a.id && s.operation_class.include?('FlakyEmail') && s.status == 'failed' }
survey_skipped = FakeFlowRunStep.store.count { |s| s.flow_run_id == fr10a.id && s.operation_class.include?('SurveyReminder') && s.status == 'skipped' }
puts "  [Part A] FlakyEmailSender failures:  #{email_failures}"   # 2
puts "  [Part A] SendSurveyReminder skipped: #{survey_skipped}"   # 1

# ── Part B: FlakyEmailSender succeeds on 2nd attempt → flow continues normally

reset_all!
Subscriber.reset!
FlakyEmailSender.set_failures(1)   # fail once, then succeed on retry

sub10b = Subscriber.create!(email: 'henry@example.com', active: true)
fr10b  = RetryBlockingFlow.call(subscriber: sub10b)

speedrun(fr10b)   # drives: attempt 1 fails → retry → attempt 2 succeeds → schedules survey

puts "  [Part B] final status:               #{fr10b.status}"   # succeeded
email_completed = FakeFlowRunStep.store.count { |s| s.flow_run_id == fr10b.id && s.operation_class.include?('FlakyEmail') && s.status == 'completed' }
puts "  [Part B] FlakyEmailSender completed: #{email_completed}"   # 1

FlakyEmailSender.reset_fail_count!

puts "\n✓ All durable flow demonstrations complete"
