#!/usr/bin/env ruby
# frozen_string_literal: true

# 08 — Durable Flows (v0.5 unified API)
#
# Covers:
#   include Easyop::Flow + subject :user   — triggers durable mode (Mode 3)
#   subject stored as subject_type/subject_id on FlowRun row
#   flow steps run durable — ctx persisted across async boundaries
#   on_exception(:reattempt!, max_reattempts: N) — automatic retry
#   on_exception(:cancel!)                 — fail immediately on step error
#   flow_run.cancel!                       — cancel from outside the flow
#   flow_run.resume!                       — resume a paused flow
#   Free composition — outer plain flow embeds a durable inner → auto-promotes
#
# Note: uses in-memory FakeFlowRun/FakeFlowRunStep/FakeScheduledTask stubs
#       (no database needed). In a Rails app, use the EasyFlowRun/EasyFlowRunStep
#       AR models generated by `rails g easyop:install`.
#
# Run: ruby examples/code/08_durable_workflow.rb

$LOAD_PATH.unshift File.expand_path('../../lib', __dir__)
require 'easyop'
require 'easyop/persistent_flow'
require 'easyop/scheduler'
require 'easyop/plugins/async'

# Time.current shim (ActiveSupport not required here)
unless Time.respond_to?(:current)
  class Time
    def self.current; now; end
  end
end

# String#constantize shim (ActiveSupport not required here)
unless ''.respond_to?(:constantize)
  class String
    def constantize; Object.const_get(self); end
  end
end

# ── Minimal AR stubs (no database) ────────────────────────────────────────────

class FakeScope
  include Enumerable

  def initialize(records) = @records = records
  def each(&blk)          = @records.each(&blk)
  def count               = @records.size
  def first               = @records.first
  def exists?             = @records.any?

  def where(*args, **conditions)
    return self if args.any? && conditions.empty?

    FakeScope.new(@records.select do |r|
      conditions.all? { |k, v| r.public_send(k) == v }
    end)
  end

  def update_all(**attrs)
    @records.each { |r| attrs.each { |k, v| r.public_send(:"#{k}=", v) } }
    @records.size
  end
end

class FakeFlowRun
  include Easyop::PersistentFlow::FlowRunModel

  attr_accessor :id, :flow_class, :context_data, :status, :current_step_index,
                :subject_type, :subject_id, :started_at, :finished_at

  @@store      = []
  @@id_counter = 0

  def self.store;   @@store;   end
  def self.reset!;  @@store = []; @@id_counter = 0; end

  def self.create!(attrs)
    obj = new
    attrs.each { |k, v| obj.public_send(:"#{k}=", v) }
    @@id_counter += 1
    obj.id = @@id_counter
    @@store << obj
    obj
  end

  def self.find(id)
    @@store.find { |r| r.id == id.to_i } or raise "FakeFlowRun #{id} not found"
  end

  def self.where(*args, **conditions)
    return FakeScope.new(@@store) if args.any? && conditions.empty?

    FakeScope.new(@@store.select do |r|
      conditions.all? { |k, v| r.public_send(k) == v }
    end)
  end

  def initialize
    @status             = 'pending'
    @current_step_index = 0
    @context_data       = '{}'
  end

  def update!(attrs)    = attrs.each { |k, v| public_send(:"#{k}=", v) } && self
  def update_columns(a) = update!(a)
  def reload            = self
end

class FakeFlowRunStep
  include Easyop::PersistentFlow::FlowRunStepModel

  attr_accessor :id, :flow_run_id, :step_index, :operation_class, :status,
                :attempt, :error_class, :error_message, :started_at, :finished_at

  @@store      = []
  @@id_counter = 0

  def self.store;   @@store;   end
  def self.reset!;  @@store = []; @@id_counter = 0; end

  def self.create!(attrs)
    obj = new
    attrs.each { |k, v| obj.public_send(:"#{k}=", v) }
    @@id_counter += 1
    obj.id = @@id_counter
    @@store << obj
    obj
  end

  def self.find(id)
    @@store.find { |r| r.id == id.to_i } or raise "FakeFlowRunStep #{id} not found"
  end

  def self.where(*args, **conditions)
    return FakeScope.new(@@store) if args.any? && conditions.empty?

    FakeScope.new(@@store.select do |r|
      conditions.all? { |k, v| r.public_send(k) == v }
    end)
  end

  def initialize
    @status  = 'running'
    @attempt = 0
  end

  def update_columns(attrs) = attrs.each { |k, v| public_send(:"#{k}=", v) } && self
end

class FakeScheduledTask
  attr_accessor :id, :operation_class, :ctx_data, :run_at, :tags, :state

  @@store      = []
  @@id_counter = 0

  def self.store;   @@store;   end
  def self.reset!;  @@store = []; @@id_counter = 0; end

  # Minimal connection stub so Scheduler._adapter_name does not raise
  def self.connection
    Struct.new(:adapter_name).new('fake_adapter')
  end

  def self.create!(attrs)
    obj = new
    attrs.each { |k, v| obj.public_send(:"#{k}=", v) if obj.respond_to?(:"#{k}=") }
    @@id_counter += 1
    obj.id    ||= @@id_counter
    obj.state ||= 'scheduled'
    @@store << obj
    obj
  end

  def self.find(id)   = @@store.find { |r| r.id == id }
  def self.where(*args, **conditions)
    return FakeScope.new(@@store) if args.any? && conditions.empty?

    FakeScope.new(@@store.select do |r|
      conditions.all? { |k, v| r.respond_to?(k) && r.public_send(k) == v }
    end)
  end

  def update_columns(attrs) = attrs.each { |k, v| public_send(:"#{k}=", v) if respond_to?(:"#{k}=") } && self

  def initialize
    @state = 'scheduled'
  end
end

# ── Configure Easyop to use our in-memory stubs ───────────────────────────────

Easyop.configure do |c|
  c.persistent_flow_model      = 'FakeFlowRun'
  c.persistent_flow_step_model = 'FakeFlowRunStep'
  c.scheduler_model            = 'FakeScheduledTask'
end

# ── Speedrun helper — drives all pending scheduled tasks synchronously ─────────

def speedrun(flow_run, max_iterations: 20)
  max_iterations.times do
    break if flow_run.terminal?
    # Find a pending task for this flow_run
    task = FakeScheduledTask.store.find do |t|
      t.state == 'scheduled' &&
        Easyop::Scheduler::Serializer.deserialize(t.ctx_data)[:flow_run_id] == flow_run.id
    end
    break unless task

    task.state = 'running'
    Easyop::PersistentFlow::Runner.execute_scheduled_step!(flow_run)
  end
  flow_run.reload
end

def reset_all!
  FakeFlowRun.reset!
  FakeFlowRunStep.reset!
  FakeScheduledTask.reset!
end

# ── Subject model — AR-compatible so Serializer can round-trip it ─────────────
# The Serializer stores AR objects as { __ar_class, __ar_id } and calls
# ClassName.find(id) on deserialization.

unless defined?(ActiveRecord)
  module ActiveRecord; class Base; end; end
end

class Subscriber < ActiveRecord::Base
  @@store = {}

  def self.store        = @@store
  def self.reset!       = (@@store = {})
  def self.find(id)     = @@store.fetch(id.to_i) { raise "Subscriber #{id} not found" }
  def self.create!(attrs)
    id = (@@store.keys.max || 0) + 1
    s  = new(id: id, **attrs)
    @@store[id] = s
    s
  end

  attr_accessor :id, :email, :active, :newsletter_opt_in

  def initialize(id: nil, email:, active:, newsletter_opt_in: true)
    @id              = id
    @email           = email
    @active          = active
    @newsletter_opt_in = newsletter_opt_in
    @@store[@id] = self if @id
  end
end

puts '─' * 50
puts '08 — Durable Flows'
puts '─' * 50

# ── Step classes ──────────────────────────────────────────────────────────────

class ValidateSubscription
  include Easyop::Operation

  def call
    ctx.fail!(error: 'Subscriber is not active') unless ctx.subscriber&.active
    ctx.plan = ctx[:plan] || 'basic'
  end
end

class ProcessPayment
  include Easyop::Operation
  plugin Easyop::Plugins::Async   # step-builder DSL (on_exception) requires Async plugin

  @@fail_count = 0

  def self.reset_fail_count!   = (@@fail_count = 0)
  def self.set_failures(n)     = (@@fail_count = n)

  def call
    if @@fail_count > 0
      @@fail_count -= 1
      raise 'payment gateway timeout'
    end

    ctx.payment_id = "pay_#{SecureRandom.hex(6)}"
    puts "  [ProcessPayment] charged #{ctx.subscriber.email} → #{ctx.payment_id}"
  end
end

class ActivateAccount
  include Easyop::Operation
  plugin Easyop::Plugins::Async   # step-builder DSL (.async) requires Async plugin

  def call
    ctx.activated = true
    puts "  [ActivateAccount] account activated for #{ctx.subscriber.email}"
  end
end

class SendWelcomeEmail
  include Easyop::Operation
  plugin Easyop::Plugins::Async   # enables .skip_if fluent builder

  def call
    puts "  [SendWelcomeEmail] welcome email sent to #{ctx.subscriber.email}"
    ctx.welcome_sent = true
  end
end

class NotifyBillingTeam
  include Easyop::Operation

  def call
    puts "  [NotifyBillingTeam] billing team notified for plan=#{ctx.plan}"
    ctx.billing_notified = true
  end
end

# ── Durable flow definition ───────────────────────────────────────────────────

class ProcessSubscription
  include Easyop::Flow

  subject :subscriber   # triggers Mode 3 — .call returns FlowRun

  flow ValidateSubscription,
       ProcessPayment.on_exception(:reattempt!, max_reattempts: 2),
       ActivateAccount,
       SendWelcomeEmail.skip_if { |ctx| !ctx[:subscriber]&.newsletter_opt_in },
       NotifyBillingTeam
end

# ── Scenario 1: Happy path — all steps complete ───────────────────────────────

puts "\nScenario 1 — happy path (newsletter opted in)"
reset_all!
ProcessPayment.reset_fail_count!
Subscriber.reset!

subscriber = Subscriber.create!(email: 'alice@example.com', active: true, newsletter_opt_in: true)
flow_run = ProcessSubscription.call(subscriber: subscriber, plan: 'pro')

puts "  returns FlowRun: #{flow_run.is_a?(FakeFlowRun)}"  # true
puts "  status:          #{flow_run.status}"               # succeeded
puts "  subject_type:    #{flow_run.subject_type}"         # Subscriber
puts "  subject_id:      #{flow_run.subject_id}"           # 1

steps = FakeFlowRunStep.store.select { |s| s.flow_run_id == flow_run.id }
puts "  step summary:"
steps.each { |s| puts "    #{s.operation_class.split('::').last.ljust(28)} #{s.status}" }

# ── Scenario 2: skip_if — newsletter opted out ────────────────────────────────

puts "\nScenario 2 — SendWelcomeEmail skipped (newsletter_opt_in: false)"
reset_all!
ProcessPayment.reset_fail_count!
Subscriber.reset!

subscriber2 = Subscriber.create!(email: 'bob@example.com', active: true, newsletter_opt_in: false)
flow_run2 = ProcessSubscription.call(subscriber: subscriber2)

puts "  status:            #{flow_run2.status}"   # succeeded
welcome = FakeFlowRunStep.store.find { |s| s.operation_class.include?('WelcomeEmail') }
puts "  SendWelcomeEmail:  #{welcome&.status}"    # skipped

# ── Scenario 3: on_exception :reattempt! — auto-retry then fail ───────────────

puts "\nScenario 3 — on_exception: :reattempt! (3 attempts then fail)"
reset_all!
ProcessPayment.set_failures(3)   # fails 3 times → exhausts max_reattempts: 2
Subscriber.reset!

subscriber3 = Subscriber.create!(email: 'carol@example.com', active: true)
flow_run3 = ProcessSubscription.call(subscriber: subscriber3)

# Runner.advance! ran ValidateSubscription then hit the first ProcessPayment failure
# → scheduled a retry. speedrun processes the retries.
speedrun(flow_run3)

puts "  status: #{flow_run3.status}"   # failed (all reattempts exhausted)
payment_attempts = FakeFlowRunStep.store.count do |s|
  s.flow_run_id == flow_run3.id && s.operation_class.include?('ProcessPayment')
end
puts "  ProcessPayment attempts: #{payment_attempts}"   # 3

# ── Scenario 4: on_exception :cancel! — immediate failure on step error ───────

puts "\nScenario 4 — on_exception: :cancel! (fail immediately)"
reset_all!
Subscriber.reset!

class PessimisticPayment
  include Easyop::Operation
  plugin Easyop::Plugins::Async   # step-builder DSL (on_exception) requires Async plugin

  def call
    raise 'gateway down'
  end
end

class CancelOnErrorFlow
  include Easyop::Flow
  subject :subscriber
  flow ValidateSubscription,
       PessimisticPayment.on_exception(:cancel!),
       ActivateAccount
end

subscriber4 = Subscriber.create!(email: 'dave@example.com', active: true)
flow_run4 = CancelOnErrorFlow.call(subscriber: subscriber4)

puts "  status:          #{flow_run4.status}"   # failed
puts "  steps completed: #{FakeFlowRunStep.store.count { |s| s.flow_run_id == flow_run4.id && s.status == 'completed' }}"
puts "  steps failed:    #{FakeFlowRunStep.store.count { |s| s.flow_run_id == flow_run4.id && s.status == 'failed' }}"

# ── Scenario 5: flow_run.cancel! — cancel from outside the flow ───────────────

puts "\nScenario 5 — flow_run.cancel! from outside"
reset_all!
Subscriber.reset!

class DelayedFlow
  include Easyop::Flow
  plugin Easyop::Plugins::Async
  subject :subscriber
  flow ValidateSubscription,
       ActivateAccount.async(wait: 86_400),   # 1-day async step → pauses here
       NotifyBillingTeam
end

subscriber5 = Subscriber.create!(email: 'eve@example.com', active: true)
flow_run5 = DelayedFlow.call(subscriber: subscriber5)
# Runner.advance! ran ValidateSubscription, then hit the async ActivateAccount
# → status is 'running', a FakeScheduledTask was created.

puts "  status after .call:        #{flow_run5.status}"   # running
puts "  scheduled tasks pending:   #{FakeScheduledTask.store.count { |t| t.state == 'scheduled' }}"  # 1

flow_run5.cancel!

puts "  status after .cancel!:     #{flow_run5.status}"   # cancelled
puts "  scheduled tasks remaining: #{FakeScheduledTask.store.count { |t| t.state == 'scheduled' }}"  # 0

# ── Scenario 6: subject stored on FlowRun row ─────────────────────────────────

puts "\nScenario 6 — subject stored on FlowRun row"
reset_all!
ProcessPayment.reset_fail_count!
Subscriber.reset!

sub6 = Subscriber.create!(email: 'frank@example.com', active: true)
fr6  = ProcessSubscription.call(subscriber: sub6)

puts "  subject_type: #{fr6.subject_type}"   # Subscriber
puts "  subject_id:   #{fr6.subject_id}"     # 1
puts "  resolved:     #{fr6.subject.email}"  # frank@example.com (re-fetched from Subscriber.find)

# ── Scenario 7: Free composition — outer plain flow auto-promotes ──────────────

puts "\nScenario 7 — free composition (plain outer embeds durable inner)"
reset_all!
ProcessPayment.reset_fail_count!
Subscriber.reset!

class PreFlightCheck
  include Easyop::Operation

  def call
    puts "  [PreFlightCheck] running pre-flight"
    ctx.preflight_done = true
  end
end

class InnerDurable
  include Easyop::Flow
  subject :subscriber
  flow ValidateSubscription, ActivateAccount
end

class OuterPlain
  include Easyop::Flow
  flow PreFlightCheck, InnerDurable   # no subject here — but inner has one
end

sub7  = Subscriber.create!(email: 'grace@example.com', active: true)
fr7   = OuterPlain.call(subscriber: sub7)

puts "  OuterPlain.call returns FlowRun: #{fr7.is_a?(FakeFlowRun)}"  # true — auto-promoted
puts "  flow_class:    #{fr7.flow_class}"    # OuterPlain
puts "  subject_type:  #{fr7.subject_type}"  # Subscriber (inherited from InnerDurable)
puts "  status:        #{fr7.status}"        # succeeded
steps7 = FakeFlowRunStep.store.select { |s| s.flow_run_id == fr7.id }
puts "  step summary:"
steps7.each { |s| puts "    #{s.operation_class.split('::').last.ljust(28)} #{s.status}" }

puts "\n✓ All durable flow demonstrations complete"
